### ISSUE TITLE
TypeError: Front.transformedAPIRequest is not a function

### ISSUE THREAD

**Issue by drummy2** [ethanresnick/json-api-example#17]
Following the exact steps for the example I get the following error when running npm run start

TypeError: Front.transformedAPIRequest is not a function
    at Object.<anonymous> (/home/ember/dai-illusion/json-api-example/src/index.js:72:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by ethanresnick** [comment]
Whoops. I forgot to remove a call to this outdated method when I updated the json-api dependency. Fixed now. Thanks!
