### ISSUE TITLE
events.js:167 throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by invious** [ethanresnick/json-api-example#18]
```
json-api-example Aymon$ npm run start

> api-example@1.0.1 start /Users/Aymon/Desktop/json-api-example
> node src/index.js

Starting up! Visit 127.0.0.1:3000 to see the docs.

events.js:167
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongoose/lib/connection.js:296:19)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-example@1.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-example@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Aymon/.npm/_logs/2018-10-29T15_58_06_653Z-debug.log
1TixUsers-MacBook-Air:json-api-example Aymon$
json-api-example Aymon$ npm run start

> api-example@1.0.1 start /Users/Aymon/Desktop/json-api-example
> node src/index.js

Starting up! Visit 127.0.0.1:3000 to see the docs.

events.js:167
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongoose/lib/connection.js:296:19)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-example@1.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-example@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Aymon/.npm/_logs/2018-10-29T15_58_06_653Z-debug.log
1TixUsers-MacBook-Air:json-api-example Aymon$json-api-example Aymon$ npm run start

> api-example@1.0.1 start /Users/Aymon/Desktop/json-api-example
> node src/index.js

Starting up! Visit 127.0.0.1:3000 to see the docs.

events.js:167
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Immediate.<anonymous> (/Users/Aymon/Desktop/json-api-example/node_modules/mongoose/lib/connection.js:296:19)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api-example@1.0.1 start: `node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api-example@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Aymon/.npm/_logs/2018-10-29T15_58_06_653Z-debug.log
1TixUsers-MacBook-Air:json-api-example Aymon$
```

**Comment by ethanresnick** [comment]
Check that you have a mongo database running. That's what this error is referring to:

> MongoError: failed to connect to server [localhost:27017] on first connect
